# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('vsi_id', models.IntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('addition_date', models.DateField(verbose_name='Addition date')),
                ('switch', models.ManyToManyField(to='devices.Device')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
