# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30, verbose_name='Hostname')),
                ('addition_date', models.DateField(verbose_name='Addition date')),
                ('model', models.CharField(choices=[('hp1910', 'HP 1910')], max_length=20, verbose_name='Model')),
                ('ports', models.PositiveIntegerField(choices=[(8, '8'), (16, '16'), (24, '24')], verbose_name='Ports number')),
                ('po', models.CharField(choices=[('BcES', 'PO BcES'), ('BES', 'PO BES'), ('CES', 'PO CES'), ('IES', 'PO IES'), ('KES', 'PO KES'), ('NES', 'PO NES'), ('OES', 'PO OES'), ('SVES', 'PO SVES'), ('SES', 'PO SES'), ('UGES', 'PO UGES')], max_length=10, verbose_name='PO name')),
                ('purchase', models.CharField(blank=True, choices=[('1272', 'Lot 1272'), ('pakasdu', 'PAK ASDU')], max_length=20)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-addition_date'],
            },
        ),
        migrations.CreateModel(
            name='AccessSwitchConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgmt_vlan', models.PositiveIntegerField(verbose_name='MGMT Vlan')),
                ('ip', models.GenericIPAddressField(verbose_name='MGMT IP')),
                ('mask', models.GenericIPAddressField(verbose_name='MGMT mask')),
                ('gw', models.GenericIPAddressField(verbose_name='MGMT gateway')),
                ('snmp_location', models.CharField(max_length=50, verbose_name='SNMP Location')),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.AccessSwitch')),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
    ]
