# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessswitch',
            name='hostname',
            field=models.CharField(max_length=30, unique=True, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='accessswitch',
            name='purchase',
            field=models.CharField(blank=True, choices=[('', ''), ('1272', 'Lot 1272'), ('pakasdu', 'PAK ASDU')], max_length=20),
        ),
        migrations.AlterField(
            model_name='accessswitchconfig',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='MGMT IP'),
        ),
    ]
